resources:
- repo: self

variables:
  - group: 'For Cypress'

pool:
  name: 'Linux-Agents' 

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens'
    inputs:
      targetFiles: cypress.json
  - script: |
      yarn
      npx cypress run --headless --spec 'cypress/**/*'
    env:
      client_id: $(cypress_client_id)
      scope: $(cypress_scope)
      client_secret: $(cypress_client_secret)
      employee_password: $(cypress_employee_password)
      manager_password: $(cypress_manager_password)
  - task: CopyFiles@2      
    condition: failed()
    inputs:
      sourceFolder: 'cypress/screenshots'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy Screenshots
  - task: PublishBuildArtifacts@1      
    condition: failed()
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: ScreenShots
    displayName: Publish Screenshots      
  - task: CopyFiles@2      
    condition: failed()
    inputs:
      sourceFolder: 'cypress/videos'
      contents: '**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: Copy Video
  - task: PublishBuildArtifacts@1      
    condition: failed()
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Videos
    displayName: Publish Videos
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/results/test-*.xml'
    condition: always()
    inputs:
      testResultsFiles: '**/test-*.xml'
