resources:
  - repo: self
pool:
  vmImage: 'ubuntu-latest'
jobs:
  - job: E2E_Tests
    workspace:
      clean: all
    steps:
      - checkout: self
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir:
          customCommand: 'ci'
        displayName: Install modules
      - script: docker run --rm -i -v $PWD:/e2e -w /e2e/ -u 1000 --entrypoint=cypress cypress/included:6.2.1 run --browser chrome --headless
        env:
          client_id: $(cypress_client_id)
          scope: $(cypress_scope)
          client_secret: $(cypress_client_secret)
          employee_password: $(cypress_employee_password)
          manager_password: $(cypress_manager_password)
        workingDirectory:
        displayName: Run e2e tests
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '/cypress/results/*.xml'
          failTaskOnFailedTests: true # Optional
        displayName: Publish test Results to AzureDevops
      - task: CopyFiles@2
        condition: failed()
        inputs:
          sourceFolder: '/cypress/screenshots'
          contents: '**/*'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: Copy Screenshots
      - task: PublishBuildArtifacts@1
        condition: failed()
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: ScreenShots
        displayName: Publish Screenshots
