# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3b1d3f25-aab2-44ff-be8c-2fad33ddb89a'
  imageRepository: 'portal/client-storybook'
  containerRegistry: 'sideniscontainerrepository.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)-$(Build.SourceBranchName)-$(Build.SourceVersion)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build and push an image to container registry
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              arguments: --build-arg REACT_APP_DT_BRANCH_NAME="$(Build.SourceBranchName)"
                --build-arg REACT_APP_DT_REPO_NAME="$(Build.Repository.Name)"
                --build-arg REACT_APP_DT_SOURCE_VERSION="$(Build.SourceVersion)"
                --build-arg REACT_APP_DT_SOURCE_VERSION_MSG="$(Build.SourceVersionMessage)"
              tags: $(tag)
          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: $(tag)