trigger: none

name: $(Date:dd-MM-yyyy_HH-mm)

# variables:
# - group: test-credentials

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
    - container: cypress
      image: cypress/browsers:node12.19.0-chrome86-ff82

jobs:
  - job: Tests
    timeoutInMinutes: 15
    displayName: E2E_Tests
    workspace:
      clean: all
    container: cypress
    steps:
      - task: Bash@3
        displayName: 'Yarn install'
        inputs:
          targetType: 'inline'
          script: 'yarn install'

      - task: Bash@3
        displayName: 'Run tests'
        inputs:
          targetType: 'inline'
          script: |
            ./node_modules/cypress/bin/cypress run --browser chrome --headless \
            --env client_id=$(cypress_client_id) \
            --env scope=$(cypress_scope) \
            --env client_secret=$(cypress_client_secret) \
            --env employee_password=$(cypress_employee_password) \
            --env manager_password=$(cypress_manager_password)
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'client/cypress/results/*.xml'
          failTaskOnFailedTests: true # Optional
