/**
 * DO NOT EDIT THIS FILE
 * This file was automatically generated from GraphQL queries and should not be edited.
 * Please change queries in *.graphql file and run codegen script if necessary.
 */
import * as Types from '../types/graphql'

import { gql } from '@apollo/client'
import * as Apollo from '@apollo/client'
export type EmployeeDetailsFragment = { __typename?: 'Employee' } & Pick<
  Types.Employee,
  | 'id'
  | 'name'
  | 'location'
  | 'country'
  | 'position'
  | 'phoneNumber'
  | 'email'
  | 'isMe'
  | 'startDate'
  | 'birthday'
>

export type GetEmployeeQueryVariables = Types.Exact<{
  email: Types.Scalars['String']
}>

export type GetEmployeeQuery = { __typename?: 'Query' } & {
  employeeByEmail?: Types.Maybe<{ __typename?: 'Employee' } & EmployeeDetailsFragment>
}

export type GetEmployeesQueryVariables = Types.Exact<{ [key: string]: never }>

export type GetEmployeesQuery = { __typename?: 'Query' } & {
  employees?: Types.Maybe<Array<{ __typename?: 'Employee' } & EmployeeDetailsFragment>>
}

export type UpdateEmployeeMutationVariables = Types.Exact<{
  input: Types.UpdateEmployeeInput
}>

export type UpdateEmployeeMutation = { __typename?: 'Mutation' } & {
  updateEmployee?: Types.Maybe<{ __typename?: 'Employee' } & Pick<Types.Employee, 'id'>>
}

export const EmployeeDetailsFragmentDoc = gql`
  fragment EmployeeDetails on Employee {
    id
    name
    location
    country
    position
    phoneNumber
    email
    isMe
    startDate
    birthday
  }
`
export const GetEmployeeDocument = gql`
  query getEmployee($email: String!) {
    employeeByEmail(email: $email) {
      ...EmployeeDetails
    }
  }
  ${EmployeeDetailsFragmentDoc}
`

/**
 * __useGetEmployeeQuery__
 *
 * To run a query within a React component, call `useGetEmployeeQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetEmployeeQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetEmployeeQuery({
 *   variables: {
 *      email: // value for 'email'
 *   },
 * });
 */
export function useGetEmployeeQuery(
  baseOptions: Apollo.QueryHookOptions<GetEmployeeQuery, GetEmployeeQueryVariables>,
) {
  return Apollo.useQuery<GetEmployeeQuery, GetEmployeeQueryVariables>(
    GetEmployeeDocument,
    baseOptions,
  )
}
export function useGetEmployeeLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<GetEmployeeQuery, GetEmployeeQueryVariables>,
) {
  return Apollo.useLazyQuery<GetEmployeeQuery, GetEmployeeQueryVariables>(
    GetEmployeeDocument,
    baseOptions,
  )
}
export type GetEmployeeQueryHookResult = ReturnType<typeof useGetEmployeeQuery>
export type GetEmployeeLazyQueryHookResult = ReturnType<typeof useGetEmployeeLazyQuery>
export type GetEmployeeQueryResult = Apollo.QueryResult<GetEmployeeQuery, GetEmployeeQueryVariables>
export const GetEmployeesDocument = gql`
  query getEmployees {
    employees {
      ...EmployeeDetails
    }
  }
  ${EmployeeDetailsFragmentDoc}
`

/**
 * __useGetEmployeesQuery__
 *
 * To run a query within a React component, call `useGetEmployeesQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetEmployeesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetEmployeesQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetEmployeesQuery(
  baseOptions?: Apollo.QueryHookOptions<GetEmployeesQuery, GetEmployeesQueryVariables>,
) {
  return Apollo.useQuery<GetEmployeesQuery, GetEmployeesQueryVariables>(
    GetEmployeesDocument,
    baseOptions,
  )
}
export function useGetEmployeesLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<GetEmployeesQuery, GetEmployeesQueryVariables>,
) {
  return Apollo.useLazyQuery<GetEmployeesQuery, GetEmployeesQueryVariables>(
    GetEmployeesDocument,
    baseOptions,
  )
}
export type GetEmployeesQueryHookResult = ReturnType<typeof useGetEmployeesQuery>
export type GetEmployeesLazyQueryHookResult = ReturnType<typeof useGetEmployeesLazyQuery>
export type GetEmployeesQueryResult = Apollo.QueryResult<
  GetEmployeesQuery,
  GetEmployeesQueryVariables
>
export const UpdateEmployeeDocument = gql`
  mutation updateEmployee($input: UpdateEmployeeInput!) {
    updateEmployee(input: $input) {
      id
    }
  }
`
export type UpdateEmployeeMutationFn = Apollo.MutationFunction<
  UpdateEmployeeMutation,
  UpdateEmployeeMutationVariables
>

/**
 * __useUpdateEmployeeMutation__
 *
 * To run a mutation, you first call `useUpdateEmployeeMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateEmployeeMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateEmployeeMutation, { data, loading, error }] = useUpdateEmployeeMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useUpdateEmployeeMutation(
  baseOptions?: Apollo.MutationHookOptions<UpdateEmployeeMutation, UpdateEmployeeMutationVariables>,
) {
  return Apollo.useMutation<UpdateEmployeeMutation, UpdateEmployeeMutationVariables>(
    UpdateEmployeeDocument,
    baseOptions,
  )
}
export type UpdateEmployeeMutationHookResult = ReturnType<typeof useUpdateEmployeeMutation>
export type UpdateEmployeeMutationResult = Apollo.MutationResult<UpdateEmployeeMutation>
export type UpdateEmployeeMutationOptions = Apollo.BaseMutationOptions<
  UpdateEmployeeMutation,
  UpdateEmployeeMutationVariables
>
