/**
 * DO NOT EDIT THIS FILE
 * This file was automatically generated from GraphQL queries and should not be edited.
 * Please change queries in *.graphql file and run codegen script if necessary.
 */
import * as Types from '../types/graphql'

import { gql } from '@apollo/client'
import * as Apollo from '@apollo/client'
const defaultOptions = {}
export type CreateExperienceMutationVariables = Types.Exact<{
  input?: Types.Maybe<Types.CreateExperienceInput>
}>

export type CreateExperienceMutation = { __typename?: 'Mutation' } & {
  createExperience?: Types.Maybe<{ __typename?: 'Experience' } & Pick<Types.Experience, 'id'>>
}

export type UpdateExperienceMutationVariables = Types.Exact<{
  input?: Types.Maybe<Types.UpdateExperienceInput>
}>

export type UpdateExperienceMutation = { __typename?: 'Mutation' } & {
  updateExperience?: Types.Maybe<{ __typename?: 'Experience' } & Pick<Types.Experience, 'id'>>
}

export type DeleteExperienceMutationVariables = Types.Exact<{
  input?: Types.Maybe<Types.DeleteExperienceInput>
}>

export type DeleteExperienceMutation = { __typename?: 'Mutation' } & {
  deleteExperience?: Types.Maybe<{ __typename?: 'Experience' } & Pick<Types.Experience, 'id'>>
}

export const CreateExperienceDocument = gql`
  mutation createExperience($input: CreateExperienceInput) {
    createExperience(input: $input) {
      id
    }
  }
`
export type CreateExperienceMutationFn = Apollo.MutationFunction<
  CreateExperienceMutation,
  CreateExperienceMutationVariables
>

/**
 * __useCreateExperienceMutation__
 *
 * To run a mutation, you first call `useCreateExperienceMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateExperienceMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createExperienceMutation, { data, loading, error }] = useCreateExperienceMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCreateExperienceMutation(
  baseOptions?: Apollo.MutationHookOptions<
    CreateExperienceMutation,
    CreateExperienceMutationVariables
  >,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useMutation<CreateExperienceMutation, CreateExperienceMutationVariables>(
    CreateExperienceDocument,
    options,
  )
}
export type CreateExperienceMutationHookResult = ReturnType<typeof useCreateExperienceMutation>
export type CreateExperienceMutationResult = Apollo.MutationResult<CreateExperienceMutation>
export type CreateExperienceMutationOptions = Apollo.BaseMutationOptions<
  CreateExperienceMutation,
  CreateExperienceMutationVariables
>
export const UpdateExperienceDocument = gql`
  mutation updateExperience($input: UpdateExperienceInput) {
    updateExperience(input: $input) {
      id
    }
  }
`
export type UpdateExperienceMutationFn = Apollo.MutationFunction<
  UpdateExperienceMutation,
  UpdateExperienceMutationVariables
>

/**
 * __useUpdateExperienceMutation__
 *
 * To run a mutation, you first call `useUpdateExperienceMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateExperienceMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateExperienceMutation, { data, loading, error }] = useUpdateExperienceMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useUpdateExperienceMutation(
  baseOptions?: Apollo.MutationHookOptions<
    UpdateExperienceMutation,
    UpdateExperienceMutationVariables
  >,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useMutation<UpdateExperienceMutation, UpdateExperienceMutationVariables>(
    UpdateExperienceDocument,
    options,
  )
}
export type UpdateExperienceMutationHookResult = ReturnType<typeof useUpdateExperienceMutation>
export type UpdateExperienceMutationResult = Apollo.MutationResult<UpdateExperienceMutation>
export type UpdateExperienceMutationOptions = Apollo.BaseMutationOptions<
  UpdateExperienceMutation,
  UpdateExperienceMutationVariables
>
export const DeleteExperienceDocument = gql`
  mutation deleteExperience($input: DeleteExperienceInput) {
    deleteExperience(input: $input) {
      id
    }
  }
`
export type DeleteExperienceMutationFn = Apollo.MutationFunction<
  DeleteExperienceMutation,
  DeleteExperienceMutationVariables
>

/**
 * __useDeleteExperienceMutation__
 *
 * To run a mutation, you first call `useDeleteExperienceMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeleteExperienceMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteExperienceMutation, { data, loading, error }] = useDeleteExperienceMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useDeleteExperienceMutation(
  baseOptions?: Apollo.MutationHookOptions<
    DeleteExperienceMutation,
    DeleteExperienceMutationVariables
  >,
) {
  const options = { ...defaultOptions, ...baseOptions }
  return Apollo.useMutation<DeleteExperienceMutation, DeleteExperienceMutationVariables>(
    DeleteExperienceDocument,
    options,
  )
}
export type DeleteExperienceMutationHookResult = ReturnType<typeof useDeleteExperienceMutation>
export type DeleteExperienceMutationResult = Apollo.MutationResult<DeleteExperienceMutation>
export type DeleteExperienceMutationOptions = Apollo.BaseMutationOptions<
  DeleteExperienceMutation,
  DeleteExperienceMutationVariables
>
